# Site settings
title: "Bovid Diversity"
description: > # this means to ignore newlines until "email:"
   a tour of bovid diversity
email: wabarr@gmail.com
avatar: images/avatar.png
base_url: http://bovids.are-awesome.com
permalink: none
tagline: All antelopes.  All the time.
google-analytics-id: '1'
#blog logo
